general:
  batch_size: 16
  dataset_name: CIFAR100
  dropout_prob: 0.1
  heads_num: 7
  num_classes: 100
  num_layers: 2  #number of head's layers, the total layers will be num_layers +1
  momentum: 0.95
  weight_decay: 0.00005
  optimizer_name: Adam
  save_path: ./yamnet_weights/ICLR_PathMNIST1.pth

  save_weights: True
  init_weight: imagnet
  save_output: [True,'/storage/yam/Multi_Dim_CP/outputs','ICLR_demo']  #Change to desired location


training_plan:
  step1:
    criterion_name: CE
    lr_features: 0.0001
    lr_heads: 0.0001
    num_epochs: 20
    trained_heads: [0]
    training_phase:
    - train_from_scratch
    - whole
  step2:
    criterion_name: CE divergence
    lr_features: 0.0001
    lr_heads: 0.0001
    num_epochs: 5
    trained_heads: ['all']
    training_phase:
      - retrain
      - part
  step3:
    criterion_name: CE
    lr_features: 0.0001
    lr_heads: 0.00001
    num_epochs: 1
    trained_heads: [ 'all' ]
    training_phase:
      - eval
      - part

